### ISSUE TITLE
Problème avec le serveur Apache tomcat

### ISSUE THREAD

**Issue by Azwaw-GHARIS** [JTeamMiage/GPI_Project#1]
Message d'erreur:
'Starting Tomcat v8.5 Server localhost' has encountered a problem 
Server Tomcat v8.( Server at localhost failed to start.

**Comment by aghiles-medane** [comment]
j'ai eu le même problème essaye   de changer le numéro de 
port.
Exemple
Tomcat admin port : 8004

HTTP/1.1                   : 8082

**Comment by Fatma-BABOU** [comment]
Je vais essayer de voir ça
