### ISSUE TITLE
Problème avec l'authentification de mon profil dans les différents commits que je fais

### ISSUE THREAD

**Issue by aghiles-medane** [JTeamMiage/GPI_Project#2]
J'ai un problème avec l'authentification de mon profil au niveau des commits que je fais.
En fait, j'ai fait beaucoup de commits (environ 16) mais lorsque vous vérifiez les contributeurs, il n'en publie que quelques-uns (seulement 12)

**Comment by Fatma-BABOU** [comment]
regarde si ton adresse email est bien vérifier sur github

**Comment by aghiles-medane** [comment]
oui effectivement c'était ca le problème , je viens de la vérifier et ca a marcher merci !!
