### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by Azwaw-GHARIS** [JTeamMiage/GPI_Project#3]
Pouvez-vous partagez l'ensemble des tests s'il vous plait !

**Comment by Fatma-BABOU** [comment]
Oui , voila le fichier test que j'ai déjà mis sur GitHub 
[TEST.pdf](https://github.com/JTeamMiage/GPI_Project/files/6260492/TEST.pdf)

**Comment by Azwaw-GHARIS** [comment]
Merci !
