### ISSUE TITLE
produits par catégories

### ISSUE THREAD

**Issue by Fatma-BABOU** [JTeamMiage/GPI_Project#4]
le client n'a pas accès aux produits par catégories (fonctionnalités disponible seulement dans le coté admin)

**Comment by aghiles-medane** [comment]
d'accord merci nous allons nous occupé de ça des que possible !!

**Comment by aghiles-medane** [comment]
après la mise a jour du code nous avons réussi a afficher les produits par catégories même pour le coté client, fait un clone du code et  vérifie comme même
