### ISSUE TITLE
Envoie des emails

### ISSUE THREAD

**Issue by Fatma-BABOU** [JTeamMiage/GPI_Project#5]
Est ce que tu peux faire un test unitaire sur la fonctionnalité : envoie des email pour la cible de routage stp!!

**Comment by Nidal-SASSI** [comment]
yes d'accord

**Comment by aghiles-medane** [comment]
Nous allons voir ça se soir avec @Azwaw-GHARIS ,je pense que c'est un problème de configuration

**Comment by Azwaw-GHARIS** [comment]
<img width="809" alt="email" src="https://user-images.githubusercontent.com/36195144/113633385-29186b80-966d-11eb-99d2-5171b250b85b.png">

**Comment by Azwaw-GHARIS** [comment]
Voila , nous avons réussi à régler le problème des E-mails , ci-joint une première version de mail
